export const category = ([
"Petits prix, grandes économies",
      " Saison Jardin",
   " Produits laitiers, oeufs, fromages",
    "Fruits, légumes",
   " Boucherie, volaille, poissonnerie",
   " Charcuterie, traiteur",
    "Pain, pâtisserie",
    "Surgelés",
    "Epicerie sucrée",
    "Epicerie salée",
   " Eaux, jus, soda, thés glacés",
    "Vins, bières, alcools",
    "Hygiène, beauté",
    "Entretien, accessoires de la maison",
    "Tout pour bébé",
    "Animalerie",
    "Produits du monde et de nos régions",
    "Bio et écologique",
    "Régimes alimentaires et nutrition",
    "Jardin, auto, brico",
    "Jouets, jeux vidéo, livres",
    "Mode, bijoux, bagagerie",
    "High-tech, Audio, TV, téléphonie",
    "Electroménager, cuisine",
    "Meuble, literie, linge de maison",
    "Nos marques",
    "Billetterie, traiteur, voyage",
])